version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: eligibility-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: visadev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # O serviço da aplicação pode ser adicionado aqui também para compor o ambiente completo
  # app:
  #   build: .
  #   container_name: eligibility-service
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/visadev
  #     - ENVIRONMENT=dev
  #   volumes:
  #     - .:/app

volumes:
  postgres_data:
